### PR TITLE
AS-4696 | Add ability to use binary content as body

### PR DESCRIPTION
**Pull request by kosala-almeda**
Needed for uploading files
Uses a `Buffer` as body instead of a `String`

### CODE REVIEW

**Comment by ynx** [comment]
1. Your PR's test is failing, did you look into whats failing it? Could it because of your change?
2. Did you transpile and update other files in this library? Please see README.md for build process, and update other files as needed.

**Comment by kosala-almeda** [comment]
> Looks like 1. is unrelated. Either way, if you could look into adding a test, it would be great. I will look into fixing the test.
Yeah, I didn't look into it, since it was already failing in `nodejs` brach.
Please let me know if you mange to fix the tests for this branch. I will add a test.

**Comment by ynx** [comment]
@kosala-almeda, I updated to Gulp 4 and the build process. It is currently building and passing tests on my machine and Travis. Please re-checkout master and submit your change. Thanks!

**Comment by kosala-almeda** [comment]
I merged the changes. But the tests are still failing.
Tests seems to fail from the beginning for `nodejs` branch (https://github.com/acquia/http-hmac-javascript/commits/nodejs).

**Comment by kosala-almeda** [comment]
I will merge the changes to `nodejs` branch. Let's fix the tests for the branch later.

**Comment by ynx** [comment]
Please ping me when the PR is up for review & merge. =)

**Pull request merged**
